// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA44gJmaXJy0Yrh3E6UV4wrsgZXv2as3AE',
    appId: '1:471429994693:web:6b5c4a2f8e9d1c7b',
    messagingSenderId: '471429994693',
    projectId: 'studio-3273559794-ea66c',
    authDomain: 'studio-3273559794-ea66c.firebaseapp.com',
    storageBucket: 'studio-3273559794-ea66c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44gJmaXJy0Yrh3E6UV4wrsgZXv2as3AE',
    appId: '1:471429994693:android:0c189da5633852721cb8ac',
    messagingSenderId: '471429994693',
    projectId: 'studio-3273559794-ea66c',
    storageBucket: 'studio-3273559794-ea66c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44gJmaXJy0Yrh3E6UV4wrsgZXv2as3AE',
    appId: '1:471429994693:ios:4c8b6d3f2e1a9c7e',
    messagingSenderId: '471429994693',
    projectId: 'studio-3273559794-ea66c',
    storageBucket: 'studio-3273559794-ea66c.firebasestorage.app',
    iosBundleId: 'com.lorecout.finwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44gJmaXJy0Yrh3E6UV4wrsgZXv2as3AE',
    appId: '1:471429994693:ios:4c8b6d3f2e1a9c7e',
    messagingSenderId: '471429994693',
    projectId: 'studio-3273559794-ea66c',
    storageBucket: 'studio-3273559794-ea66c.firebasestorage.app',
    iosBundleId: 'com.lorecout.finwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA44gJmaXJy0Yrh3E6UV4wrsgZXv2as3AE',
    appId: '1:471429994693:android:0c189da5633852721cb8ac',
    messagingSenderId: '471429994693',
    projectId: 'studio-3273559794-ea66c',
    storageBucket: 'studio-3273559794-ea66c.firebasestorage.app',
  );
}
